### PR TITLE
Update fip-0013.md

### PR DESCRIPTION
**Pull request by adsorptionenthalpy**
FIO Address does not exist, shouldn't this be a 404?

### CODE REVIEW

**Comment by pawmmm** [comment]
Aren't we using 400 for invalid or not existent FIO Address elsewhere and 400 for when you are trying to get results using a valid query, but there are no results.

**Comment by adsorptionenthalpy** [comment]
Maybe I got this wrong... I thought we were using 404 for a situation where a fio address hash could not be located. The error says FIO Address does not exist

**Comment by pawmmm** [comment]
Perhaps it is that way somewhere, but the convention is to return 400 if what you specified is not valid or does not exist, and 404 when input parameters are valid, but what you are looking for is not there. get_pub_address is a good example: https://developers.fioprotocol.io/api/api-spec/reference/get-pub-address/get-pub-address

**Comment by adsorptionenthalpy** [comment]
Okay. Thanks for clarifying.

**Pull request closed without merging**
