### PR TITLE
address comments made on the initial pull request

### PR DESCRIPTION
**Pull request by edrotthoff**
this PR attempts to address pawels comments on the initial PR for this FIP

### CODE REVIEW

**Comment by lukestokes** [comment]
Looks like this also includes FIP6?

**Comment by edrotthoff** [comment]
Let me remove fip6 from that, its not meant to have it…accidental commit this am

**Comment by pawmmm** [comment]
@edrotthoff is this still relevant?

**Comment by lukestokes** [comment]
@edrotthoff I'll leave this to you to resolve conflicts. Thanks.

**Comment by pawmmm** [comment]
Obsolete

**Pull request closed without merging**
